apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: message-pusher-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-ceph-block

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-pusher
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-pusher
  template:
    metadata:
      labels:
        app: message-pusher
    spec:
      hostNetwork: true
      containers:
        - name: message-pusher
          image: justsong/message-pusher:v0.4.10
          ports:
            - containerPort: 3000
          env:
            - name: TZ
              value: Asia/Shanghai
          volumeMounts:
            - name: message-pusher-storage
              mountPath: /data
      volumes:
        - name: message-pusher-storage
          persistentVolumeClaim:
            claimName: message-pusher-pvc
    

---
apiVersion: v1
kind: Service
metadata:
  name: message-pusher
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30012

  selector:
    app: message-pusher
