apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ql-data-pvc
  labels:
    app: qinglong
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  # 根据需要调整存储大小
  storageClassName: manual-ql  # 使用 rook-block 存储类

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: ql-data-pv
spec:
  storageClassName: manual-ql
  capacity:
    storage: 5Gi  # 根据需要调整存储大小
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /nfsdata/qldata  # 这里指定主机上的路径



---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: qinglong
  labels:
    app: qinglong
spec:
  replicas: 1  # 副本数
  selector:
    matchLabels:
      app: qinglong
  template:
    metadata:
      labels:
        app: qinglong
    spec:
      hostNetwork: true
      containers:
      - name: qinglong
        image: whyour/qinglong:2  # 或者使用 debian 版本
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: "0.5"
        ports:
        - containerPort: 5700
        env:
        - name: TZ
          value: "Asia/Shanghai"
        - name: QlBaseUrl
          value: '/'  # 设置基础 URL
        volumeMounts:
        - name: ql-data
          mountPath: /ql/data  # 将 PVC 挂载到容器内的路径
      volumes:
      - name: ql-data
        persistentVolumeClaim:
          claimName: ql-data-pvc  # 指定 PVC 名称

---

apiVersion: v1
kind: Service
metadata:
  name: qinglong
spec:
  type: NodePort  # 可以根据需要选择 Service 类型
  ports:
    - port: 5700
      targetPort: 5700
      protocol: TCP
      nodePort: 30021  # 可以根据需要指定 NodePort
  selector:
    app: qinglong
