apiVersion: v1
kind: PersistentVolume
metadata:
  name: wxedge-storage
spec:
  capacity:
    storage: 50Gi # 根据需要调整存储大小
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/wxedge/ # 替换为你的磁盘路径

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wxedge-storage-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi # 确保与 PersistentVolume 的大小匹配

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wxedge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wxedge
  template:
    metadata:
      labels:
        app: wxedge
    spec:
      containers:
      - name: wxedge
        image: images-cluster.xycloud.com/wxedge/wxedge:latest
        ports:
          - containerPort: 18888 # 根据需要更改端口
        volumeMounts:
          - name: storage
            mountPath: /storage
        securityContext:
          privileged: true
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: wxedge-storage-claim
      hostNetwork: true
      hostIPC: true
      hostPID: true
