#apiVersion: v1
#kind: Namespace
#metadata:
#  name: happy

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  namespace: happy
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /nfsdata/happydata/mongodb

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: happy
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: happy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:4.4.29
        args: ["--auth"]
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "admin"          # 设置管理员用户名
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "admin"  # 设置管理员密码
        volumeMounts:
        - mountPath: /data/db
          name: mongodb-storage
      volumes:
      - name: mongodb-storage
        persistentVolumeClaim:
          claimName: mongodb-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: happy
spec:
  type: NodePort
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 37017
  selector:
    app: mongodb

---


apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-pv
  namespace: happy
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /nfsdata/happydata/elasticsearch

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-pvc
  namespace: happy
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: happy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - env:
        - name: discovery.type
          value: single-node
        name: elasticsearch
        image: elasticsearch:7.6.1
        ports:
        - containerPort: 9200
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: es-storage
      volumes:
      - name: es-storage
        persistentVolumeClaim:
          claimName: es-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: happy
spec:
  type: NodePort
  ports:
    - port: 9200
      targetPort: 9200
      nodePort: 39200
  selector:
    app: elasticsearch
